#formato:
#id,displayName,width,height,fps,bitrateKbps,keyIntMax,encoderPreset,encoderTune,leakyQueue
#
#Remote Desktop Server configuration
#Mon Apr 20 13:44:15 BRT 2026
connection.profile=WIFI
connection.profile.LAN=LAN,Rede local,1920,1080,30,6000,30,ultrafast,zerolatency,false
connection.profile.SATELLITE_1=SATELLITE_1,Sat\u00E9lite 1,1024,576,10,1000,20,veryfast,zerolatency,true
connection.profile.SATELLITE_2=SATELLITE_2,Sat\u00E9lite 2,1280,720,12,1400,24,veryfast,zerolatency,true
connection.profile.SATELLITE_3=SATELLITE_3,Sat\u00E9lite 3,1280,720,15,1800,30,veryfast,zerolatency,true
connection.profile.WIFI=WIFI,Wi-Fi,1280,720,20,2500,30,veryfast,zerolatency,true
control.port=5000
handshake.port=7000
